### ISSUE TITLE
We should NOT optimize for native arch in deb builds

### ISSUE THREAD

**Issue by jlblancoc** [borglab/gtsam-packaging#10]
We should explicitly set `GTSAM_BUILD_WITH_MARCH_NATIVE` to `OFF` to ensure binary portability and avoid Eigen crashes.

It should in fact be the default in the CMake script, but this may break status quo, so it should be left for the next major/minor release (?). 

Anyway, right now `debian/rules` in the PPA,  e.g. [here](https://launchpadlibrarian.net/502087684/buildlog_ubuntu-bionic-amd64.gtsam_4.1.0-1ubuntu1~30.gbp6f4708_BUILDING.txt.gz), uses: 

```
dh_auto_configure --  -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DGTSAM_BUILD_EXAMPLES_ALWAYS=OFF -DGTSAM_BUILD_TESTS=OFF -DGTSAM_BUILD_WRAP=OFF -DGTSAM_BUILD_DOCS=OFF -DGTSAM_INSTALL_CPPUNITLITE=OFF -DGTSAM_INSTALL_GEOGRAPHICLIB=OFF -DGTSAM_BUILD_TYPE_POSTFIXES=OFF -DGTSAM_USE_SYSTEM_EIGEN=ON
```

Please, @berndpfrommer , could you update/merge the `debian/*` files to those in [this branch](https://github.com/borglab/gtsam-packaging/tree/debian/debian), which already add that flag?

**Comment by jlblancoc** [comment]
Example error I just found due to this issue. Beginners may be totally mystified by this error coming from nowhere without apparent reason :-) 

```
xxx: /usr/include/eigen3/Eigen/src/Core/MapBase.h:191: void Eigen::MapBase<Derived, 0>::checkSanity(typename Eigen::internal::enable_if<(Eigen::internal::traits<OtherDerived>::Alignment > 0), void*>::type) const [with T = Eigen::Map<Eigen::Matrix<double, 3, 6, 0, 3, 6>, 32, Eigen::Stride<0, 0> >; Derived = Eigen::Map<Eigen::Matrix<double, 3, 6, 0, 3, 6>, 32, Eigen::Stride<0, 0> >; typename Eigen::internal::enable_if<(Eigen::internal::traits<OtherDerived>::Alignment > 0), void*>::type = void*]: Assertion `( ((internal::UIntPtr(m_data) % internal::traits<Derived>::Alignment) == 0) || (cols() * rows() * innerStride() * sizeof(Scalar)) < internal::traits<Derived>::Alignment ) && "data is not aligned"' failed.
```

**Comment by berndpfrommer** [comment]
On the flip side, if you build gtsam *without* -march native, and then link it against an object that has been build *with* -march native, you get  "double free or corruption errors". I don't know a good way around it.

Other GTSAM users have bumped into this as well.

https://github.com/MIT-SPARK/Kimera-RPGO/issues/41

**Comment by jlblancoc** [comment]
Good point...

However, building for a specific architecture would need different binaries for processors up to SSE3, AVX, AVX2, etc. :-( 
Probably the best solution, IMO, is to provide *generic* binaries for all processors, then if someone needs to "super optimizations" instruct them to generate their own build for each one's machine... 
Thoughts?

**Comment by jlblancoc** [comment]
Hi! 
@berndpfrommer : The [ppa](https://launchpad.net/~borglab/+archive/ubuntu/gtsam-develop) hasn't been updated in a while... was it supposed to be uploaded automatically from github actions from your fork, or not? Perhaps I misunderstood the setup... :-)

**Comment by berndpfrommer** [comment]
Let me look at it, maybe something broke. It should update/upload automatically....
Busy today, will look at it tomorrow.

**Comment by borglab-launchpad** [comment]
@jlblancoc good catch!
The build process failed because for the first time somebody made changes to binary files (some python related .png files) which cannot be captured as diffs. So when the changes between develop branch and pristine tar ball were computed, some of the differences were captured in debian/source/include-binaries, which wasn't properly committed, and thus caused the script to fail.
I have pushed an attempted fix which will be exercised once the next update to the develop branch occurs. It may not work the first time round, but I'll keep an eye on it and follow up.

**Comment by borglab-launchpad** [comment]
checked again today, still failing, because of ppa version number being ahead of github version number. Bumped it by hand, hope that helps. Should run tomorrow if anything new is committed to gtsam develop.

**Comment by jlblancoc** [comment]
I tested it today and: 
- your PPA build was successful!! :+1: 
- The newly generated packages include the no-"optimize native" flag,
- I tested the -dev packages and gtsam was successfully found from a 3rd party user project, compiled, linked and ran ok! :+1: 

Wonderful! :-)
