### ISSUE TITLE
Nightly Build Not Working

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam-packaging#12]
It seems like the nightly build defined in the Github Actions workflow is not triggering.
The last version of `gtsam-develop` published on Launchpad shows as `2021-01-03` which is 2.5 months ago.

**Comment by berndpfrommer** [comment]
ok. Traveling right now, will look at it when I'm back.

**Comment by berndpfrommer** [comment]
Logged on as the borglab-launchpad user on github to look at the output of the actions, and this is what I saw:

![image](https://user-images.githubusercontent.com/6206826/111875190-ed905880-896e-11eb-803a-bdf23522bff2.png)

I guess the packaging repo itself is untouched so it stops running the nightly jobs. Let's see if that gets it started again and if everything still works. Next is to find a work-around. It's a bit silly that the clean separation between packaging and the code itself actually breaks the nightly jobs.

**Comment by borglab-launchpad** [comment]
This got the packaging to work now, so the source package is built successfully and uploaded to Canonical's build servers.
However, the compilation of the package itself fails with the following error message. Any idea what this is about?

```
-- Install prefix: /usr
CMake Error at cmake/GtsamTesting.cmake:286 (add_executable):
  add_executable cannot create target "ISAM2_SmartFactorStereo_IMU" because
  another target with the same name already exists.  The existing target is
  an executable created in source directory
  "/<<PKGBUILDDIR>>/examples".  See documentation for policy
  CMP0002 for more details.
Call Stack (most recent call first):
  cmake/GtsamTesting.cmake:55 (gtsamAddExesGlob_impl)
  gtsam_unstable/examples/CMakeLists.txt:5 (gtsamAddExamplesGlob)


CMake Error at cmake/GtsamTesting.cmake:287 (target_link_libraries):
  Attempt to add link library "gtsam_unstable" to target
  "ISAM2_SmartFactorStereo_IMU" which is not built in this directory.

  This is allowed only when policy CMP0079 is set to NEW.
Call Stack (most recent call first):
  cmake/GtsamTesting.cmake:55 (gtsamAddExesGlob_impl)
  gtsam_unstable/examples/CMakeLists.txt:5 (gtsamAddExamplesGlob)


CMake Error at cmake/GtsamTesting.cmake:295 (add_custom_target):
  add_custom_target cannot create target "ISAM2_SmartFactorStereo_IMU.run"
  because another target with the same name already exists.  The existing
  target is a custom target created in source directory
  "/<<PKGBUILDDIR>>/examples".  See documentation for policy
  CMP0002 for more details.
Call Stack (most recent call first):
  cmake/GtsamTesting.cmake:55 (gtsamAddExesGlob_impl)
  gtsam_unstable/examples/CMakeLists.txt:5 (gtsamAddExamplesGlob)


-- Wrote /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/GTSAMConfig.cmake

```

**Comment by varunagrawal** [comment]
My guess is someone made a PR and we hit merge too soon. Let me take a look.

**Comment by varunagrawal** [comment]
Also, regarding the Github Actions packaging flow, let me know if you find something since I am planning something similar for the python packages and it would be nice to know my options.

**Comment by varunagrawal** [comment]
I tried building the package locally using the instructions from [modifying-the-packaging](https://github.com/borglab/gtsam-packaging#modifying-the-packaging) but I run into `gbp` issues:

```sh
gbp:info: Performing the build
 dpkg-buildpackage -us -uc -ui -i -I -S -sa
dpkg-buildpackage: info: source package gtsam
dpkg-buildpackage: info: source version 4.0.3-1ubuntu1~1.gbpa6d313
dpkg-buildpackage: info: source distribution xenial
dpkg-buildpackage: info: source changed by Borglab Builder <borglab.launchpad@gmail.com>
 dpkg-source -i -I --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: libcpputest-dev libgeographic-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I -S -sa failed
gbp:error: 'debuild -i -I -k95C3A575ABC855CE7D271B2A5C288700CB82A210 -S -sa' failed: it exited with 29
~/borglab ~/borglab/gtsam-packaging
Can't open /home/varun/borglab/gtsam_*_source.changes
~/borglab/gtsam-packaging
gbp:info: Continuing from commit 'a6d313b13b41359d4d69efb4516a6d4b7ecf6419'
gbp:info: Changelog 4.0.3-1ubuntu1~2.gbp7f93b2 (snapshot #2) prepared up to 7f93b2f
sleeping for 1min ....
[ubuntu/snapshot 9c14de6f2] modified changelog for distro bionic
 1 file changed, 9 insertions(+)
gbp:info: Performing the build
 dpkg-buildpackage -us -uc -ui -i -I -S -sa
dpkg-buildpackage: info: source package gtsam
dpkg-buildpackage: info: source version 4.0.3-1ubuntu1~2.gbp7f93b2
dpkg-buildpackage: info: source distribution bionic
dpkg-buildpackage: info: source changed by Borglab Builder <borglab.launchpad@gmail.com>
 dpkg-source -i -I --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: libcpputest-dev libgeographic-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I -S -sa failed
gbp:error: 'debuild -i -I -k95C3A575ABC855CE7D271B2A5C288700CB82A210 -S -sa' failed: it exited with 29
~/borglab ~/borglab/gtsam-packaging
Can't open /home/varun/borglab/gtsam_*_source.changes
~/borglab/gtsam-packaging
gbp:info: Continuing from commit '7f93b2f82b8d5db2a0038a0d057dc1ef4be0fe9c'
gbp:info: Changelog 4.0.3-1ubuntu1~3.gbp9c14de (snapshot #3) prepared up to 9c14de6
sleeping for 1min ....
[ubuntu/snapshot 49bf53714] modified changelog for distro focal
 1 file changed, 8 insertions(+)
gbp:info: Performing the build
 dpkg-buildpackage -us -uc -ui -i -I -S -sa
dpkg-buildpackage: info: source package gtsam
dpkg-buildpackage: info: source version 4.0.3-1ubuntu1~3.gbp9c14de
dpkg-buildpackage: info: source distribution focal
dpkg-buildpackage: info: source changed by Borglab Builder <borglab.launchpad@gmail.com>
 dpkg-source -i -I --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: libcpputest-dev libgeographic-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I -S -sa failed
gbp:error: 'debuild -i -I -k95C3A575ABC855CE7D271B2A5C288700CB82A210 -S -sa' failed: it exited with 29
~/borglab ~/borglab/gtsam-packaging
Can't open /home/varun/borglab/gtsam_*_source.changes
~/borglab/gtsam-packaging
gbp:info: Continuing from commit '9c14de6f2a144c87b52d82b29353379ee958722c'
gbp:info: Changelog 4.0.3-1ubuntu1~4.gbp49bf53 (snapshot #4) prepared up to 49bf537
sleeping for 1min ....
```

@berndpfrommer can you please try locally as well and see if it works for you?

**Comment by berndpfrommer** [comment]
ok. I am on a campground now with terrible wifi and no cell signal. Cannot
git pull. Hope to have better connectivity tonight.

**Comment by berndpfrommer** [comment]
Sorry, new campground isn't any better. Will have to wait another 4 days.

**Comment by varunagrawal** [comment]
No worries. Enjoy your weekend, this is not high priority. :)

**Comment by borglab-launchpad** [comment]
The build completes on my Ubuntu 20.04 machine, so there is something weird going on when the packages are built on Canonical's servers.
There, the cmake already produces errors, but then the build continues (I would have expected it to abort). Also, further down the log when it compiles there are complaints that look like compiler version issues:

```
/usr/bin/c++    -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DCOMPILER_HAS_WMISSING_OVERRIDE   -Wmissing -o CMakeFiles/cmTC_5e201.dir/src.cxx.o -c /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option '-Wmissing'; did you mean '-Waliasing'?

```
I'm working on it now but it may take several days to get this working because I have to use the launchpad servers to debug this.

**Comment by borglab-launchpad** [comment]
The first time the build breaks is with this commit:
https://github.com/borglab/gtsam/commit/a567a570ede8a8e1ba641eba4b5245af5a2d045e

**Comment by borglab-launchpad** [comment]
More diagnosis: this is a bug with the packaging scripts, not with the GTSAM source tree. Apparently the script as it is right now does not *remove* files when they disappear from the source tree. In the commit referred to above, the file is moved to another location, and therefore shows up twice in the source tree.
I pushed a fix for this into the repo, let's see how far that gets us.
https://github.com/borglab-launchpad/gtsam-packaging/commit/e77fd30f2b9099aa47eda505ce41c892a972d6ca

**Comment by varunagrawal** [comment]
Great sleuthing. We should add a status badge to the main repo to catch these sooner or better yet, somehow get the CI in GTSAM to dry run the packaging.

**Comment by borglab-launchpad** [comment]
The build last night succeeded. I'm trying to find out if there is a way I can get notified when the builds stop working. This will have to happen at the launchpad level because that's where the build actually failed. The source packaging succeeded.

**Comment by borglab-launchpad** [comment]
I set up a filter on the gmail account such that any messages containing the words "Build failed" will be forwarded to me. Closing this issue for now.

**Comment by jlblancoc** [comment]
Hi! 

Unfortunately, it seems the PPA builds are frozen again :-( 
 https://launchpad.net/~borglab/+archive/ubuntu/gtsam-develop

**Comment by borglab-launchpad** [comment]
The workflow that builds the package is automatically disabled by github after 60 days. I set my calendar now to remind me every 60 days to re-enable the workflow.

**Comment by jlblancoc** [comment]
Ok, thanks! I imagined it was that... anything special to do to re-enable it? 
Earlier today I did a tiny commit in the hope it worked to reactive it, but if there was a "click-here button" it would be better :-)
