### ISSUE TITLE
Non-TBB Nightly Build?

### ISSUE THREAD

**Issue by varunagrawal** [borglab/gtsam-packaging#14]
Is it possible to get a non-TBB enabled nightly build going? There are some breaking changes in TBB which we have not yet fixed so having a non-TBB version (alongwith the current TBB-enabled version) would be great, especially for CI stuff.

**Comment by berndpfrommer** [comment]
I don't quite now how your CI setup works as I have only dealt with the debian/ubuntu packaging so far.

So you want to have another ubuntu PPA that has a nightly version of gtsam, but with different build options (non-tbb). I can certainly set that up, but how does that figure into CI? Would this be for other packages that currently use the nightly builds? Because me setting up a nightly PPA build will not affect/help/change your gtsam CI setup.

**Comment by varunagrawal** [comment]
For the CI, I currently have to install TBB separately even though we don't need it, else compiling code that depends on GTSAM just fails due to the missing dependency.

Having the non TBB version would save us the effort of maintaining TBB in the CI as well as improve the CI speed due to one less step. 😊

**Comment by borglab-launchpad** [comment]
working on it...

**Comment by varunagrawal** [comment]
@berndpfrommer any updates on this? Please do let me know when this issue is fixed so I can update the CI accordingly.

**Comment by borglab-launchpad** [comment]
There is now a new gtsam-no-tbb package in the gtsam nightly build ppa. Could you please check it out?

**Comment by varunagrawal** [comment]
I see it on launchpad but running 
```
sudo add-apt-repository ppa:borglab/gtsam-develop
sudo apt-get update
sudo apt-get -y install gtsam-no-tbb
```

gives me 
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gtsam-no-tbb
```

Guess I have to wait a little longer for availability?

**Comment by berndpfrommer** [comment]
I tested right away and it worked for me. can you do "apt search gtsam"
?

**Comment by varunagrawal** [comment]
~~Yup I see it. I guess my initial hunch was right and Launchpad just needed some time to update all the servers.~~

I see my mistake, it should be `libgtsam-no-tbb-dev` or `libgtsam-no-tbb4`. Shouldn't it be `libgtsam4-no-tbb` (just a nitpick)?
