### ISSUE TITLE
set up PPAs for nightly builds and releases

### ISSUE THREAD

**Issue by berndpfrommer** [borglab/gtsam-packaging#6]
Is there already an official Ubuntu Personal Package Archive (PPA) for download?
I see Jose has set up a PPA, but it may make sense to create one under borglab with shared ownership.

How about we create a new Ubuntu PPA user, and put several PPAs underneath there:

- one for nightly snapshots
- one for GTSAM 4.1.0 (last release)
- maybe one for the latest 4.0.x (x = 3?)

**Comment by jlblancoc** [comment]
Absolutely agree. At least, I would create the PPAs:
* `gtsam-develop` (nightly builds from git branch develop)
* `gtsam-stable`: last stable release. 

And more if Frank's think they are useful. 

@dellaert Do you agree with Bernd's plan? 

@berndpfrommer : I think the only way to do this is to create a new gmail account (with a password shared by those involved in the process), then register at LaunchPad with a **username** `borglab` and a shared password once again, then start adding the PPAs inside that user. Or do you know of another alternative so we can reuse our current LaunchPad Users and still create an "organization" named `borglab`?

**Comment by dellaert** [comment]
I mostly use GTSAM on Mac so y’all are in charge :-)

**Comment by jlblancoc** [comment]
@berndpfrommer @dellaert You should have access to a shared note with details on https://keep.google.com/ let me know if you have problems accessing it. 

Empty PPAs are created now: https://launchpad.net/~borglab

**Comment by jlblancoc** [comment]
The [new PPA](https://launchpad.net/~borglab/+archive/ubuntu/gtsam-develop/+packages) seems to work pretty well :-) 
I've tested building programs with its binaries without problems. 

@dellaert 
Should we publicize it on the gtsam website, instead of pointing to my former personal PPA? 
I think it can be done via a PR to the gtsam.org repo, right?

**Comment by berndghost** [comment]
@jlblancoc I want to merge in your changes to the debian files this weekend (sorry, super busy at work) and set up the release ppas as well. Can we hold off with publicizing the new ppa's until that's been done and tested? Just want to avoid a poor out-of-the-box experience when crossing over to the new ppas.

**Comment by berndpfrommer** [comment]
@jlblancoc I want to merge in your changes to the debian files this weekend (sorry, super busy at work) and set up the release ppas as well. Can we hold off with publicizing the new ppa's until that's been done and tested? Just want to avoid a poor out-of-the-box experience when crossing over to the new ppas.

**Comment by jlblancoc** [comment]
Sure, no problem! We are all mostly volunteers here :-) 
Let's give it one more week for testing after your next changes before publicizing it.

**Comment by berndpfrommer** [comment]
Merged @jlblancoc changes to the debian files and set up new a ppa for the 4.0 release.

https://launchpad.net/~borglab/+archive/ubuntu/gtsam-develop
https://launchpad.net/~borglab/+archive/ubuntu/gtsam-release-4.0

I'll set up another ppa when 4.1 is officially released.
