### ISSUE TITLE
disable actions for this repo

### ISSUE THREAD

**Issue by berndpfrommer** [borglab/gtsam-packaging#7]
Since this repo has workflow, it will try to run nightly builds. These will fail since there is no PPA configured, nor is the GPG key there. I can't do it, but somebody with permissions needs to go into the repo settings and disable Actions:

![image](https://user-images.githubusercontent.com/6206826/94915034-25b3e580-047a-11eb-9885-43f3c4571275.png)

**Comment by dellaert** [comment]
Done
