### ISSUE TITLE
build fails, need admin access or secret key deposited

### ISSUE THREAD

**Issue by berndpfrommer** [borglab/gtsam-packaging#9]
The nightly builds fail right now because I do not have privileges to see the "settings" menu, and hence cannot deposit the secret key as required. There are two options:

1) elevate my privileges to "admin" (I hope this can be done on a per-repo basis, only for this repo)
2) deposit the secret GPG key as per the instructions below (from the README.md). I have sent the below-mentioned secret key to @jlblancoc already, and I can also send it to @dellaert if you can send me your gpg public key for encryption (the secret key has no passphrase, so I don't want to send it around unencrypted).

Bernd

Deposit the secret GPG key on github:
Now go to your github GTSAM packaging repo (created in the first step), and create a "secret" under the repo. Note: do not deposit the key as a GPG key under your user, but add it as a secret to the particular GTSAM packaging repo created earlier, e.g. gtsam-packaging. There, create a secret called "GPG_PRIVATE_KEY" and cut and paste the armored key, including begin/end lines into the field below the secret.

**Comment by berndpfrommer** [comment]
Never mind, I was confused. The build actually happens under the launchpad github user.

**Comment by jlblancoc** [comment]
Yes, it works! :tada: 
I'll test it for a while as a user to see if it works smoothly before requesting it to be shown as the official PPA instead of my older PPA. 

@berndpfrommer : Did you integrate my latest edits in [this branch](https://github.com/borglab/gtsam-packaging/commits/debian/debian)? How should I make sure future changes to `debian/*` get used?

**Comment by berndpfrommer** [comment]
Your latest edits have not been incorporated. Since the automatic builds are tedious to debug I was going to fold your latest debian changes into the "release" build, which at this moment doesn't exist yet. Will try to look at it before end of the week.

Unfortunately I think we should have several "release" build ppas. Version 4.0 would be one (currently we are at 4.0.3?) and 4.1 the other one. I am not sure 4.1 is officially released? I just saw a tag saying "release candidate" and grabbed that one. But given that every new package in a release overwrites the previous one it would be useful to have separate ppas for e.g. 4.0 and 4.1, such that if people run into difficulties with 4.1 they can revert back to the 4.0 ppa.

**Comment by berndpfrommer** [comment]
Regarding your question: I will make instructions on how to modify the debian directory and push it back into the packaging directory.
